// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_gpu_top.h for the primary calling header

#ifndef VERILATED_VTB_GPU_TOP___024ROOT_H_
#define VERILATED_VTB_GPU_TOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb_gpu_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_gpu_top___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_gpu_top__DOT__clk;
        CData/*0:0*/ tb_gpu_top__DOT__rst_n;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__sched_valid;
        CData/*1:0*/ tb_gpu_top__DOT__dut__DOT__pc_wen;
        CData/*1:0*/ tb_gpu_top__DOT__dut__DOT__pc_wen_fetch;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__if_warp;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__if_valid;
        CData/*4:0*/ tb_gpu_top__DOT__dut__DOT__id_rs1_addr_out;
        CData/*4:0*/ tb_gpu_top__DOT__dut__DOT__id_rs2_addr_out;
        CData/*4:0*/ tb_gpu_top__DOT__dut__DOT__id_rd_addr;
        CData/*3:0*/ tb_gpu_top__DOT__dut__DOT__id_alu_op;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__id_alu_src;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__id_mem_read;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__id_mem_write;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__id_reg_write;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__id_branch;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__id_mem_to_reg;
        CData/*2:0*/ tb_gpu_top__DOT__dut__DOT__id_funct3;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__id_jal;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__id_warp_id;
        CData/*1:0*/ tb_gpu_top__DOT__dut__DOT__warp_stall;
        CData/*7:0*/ tb_gpu_top__DOT__dut__DOT__lane_branch_taken;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT____Vcellinp__regfiles__BRA__0__KET____DOT__u_regfile__wr_en;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT____Vcellout__lanes__BRA__0__KET____DOT__u_lane__branch_taken;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT____Vcellout__lanes__BRA__0__KET____DOT__u_lane__dmem_wen;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT____Vcellout__lanes__BRA__0__KET____DOT__u_lane__dmem_ren;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__u_scheduler__DOT__rr_ptr;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__u_scheduler__DOT__next_warp;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__u_scheduler__DOT__any_ready;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__u_scheduler__DOT__unnamedblk5__DOT__unnamedblk6__DOT__candidate;
        CData/*3:0*/ tb_gpu_top__DOT__dut__DOT__u_decode__DOT__alu_op;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__u_decode__DOT__alu_src;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__u_decode__DOT__mem_read;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__u_decode__DOT__mem_write;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__u_decode__DOT__reg_write;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__u_decode__DOT__branch;
        CData/*0:0*/ tb_gpu_top__DOT__dut__DOT__u_decode__DOT__mem_to_reg;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v0;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v0;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v0;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v0;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v1;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v1;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v1;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v1;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v2;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v2;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v2;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v2;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v3;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v3;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v3;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v3;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v4;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v4;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v4;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v5;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v5;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v5;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v6;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v6;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v7;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v7;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v7;
    };
    struct {
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v7;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v8;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v8;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v8;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v8;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v9;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v9;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v9;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v9;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v10;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v10;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v10;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v10;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v11;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v11;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v11;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v12;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v12;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v12;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v13;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v13;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v14;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v14;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v14;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v14;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v15;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v15;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v15;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v15;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v16;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v16;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v16;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v16;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v17;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v17;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v17;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v17;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v18;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v18;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v18;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v19;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v19;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v19;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v20;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v20;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v21;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v21;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v21;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v21;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v22;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v22;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v22;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v22;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v23;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v23;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v23;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v23;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v24;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v24;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v24;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v24;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v25;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v25;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v25;
    };
    struct {
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v26;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v26;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v26;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v27;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v27;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v28;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v28;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v28;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v28;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v29;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v29;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v29;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v29;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v30;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v30;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v30;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v30;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v31;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v31;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v31;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v31;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v32;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v32;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v32;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v33;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v33;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v33;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v34;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v34;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v35;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v35;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v35;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v35;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v36;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v36;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v36;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v36;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v37;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v37;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v37;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v37;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v38;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v38;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v38;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v38;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v39;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v39;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v39;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v40;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v40;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v40;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v41;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v41;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v42;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v42;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v42;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v42;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v43;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v43;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v43;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v43;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v44;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v44;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v44;
    };
    struct {
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v44;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v45;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v45;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v45;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v45;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v46;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v46;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v46;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v47;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v47;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v47;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v48;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v48;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v49;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v49;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v49;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v49;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v50;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v50;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v50;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v50;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v51;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v51;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v51;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v51;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v52;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v52;
        CData/*7:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v52;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v52;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v53;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v53;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v53;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v54;
        CData/*4:0*/ __Vdlyvlsb__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v54;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v54;
        CData/*7:0*/ __Vdlyvdim1__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v55;
        CData/*0:0*/ __Vdlyvset__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v55;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_gpu_top__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_gpu_top__DOT__rst_n__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v4;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v5;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v11;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v12;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v18;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v19;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v25;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v26;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v32;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v33;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v39;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v40;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v46;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v47;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v53;
        SData/*15:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v54;
        IData/*31:0*/ tb_gpu_top__DOT__pass_count;
        IData/*31:0*/ tb_gpu_top__DOT__fail_count;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__sched_active_pc;
        QData/*63:0*/ tb_gpu_top__DOT__dut__DOT__pc_next;
        QData/*63:0*/ tb_gpu_top__DOT__dut__DOT__pc_next_fetch;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__if_instr;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__if_pc;
    };
    struct {
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__id_pc;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__id_rs1_out;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__id_rs2_out;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__id_imm;
        VlWide<8>/*255:0*/ tb_gpu_top__DOT__dut__DOT__dmem_addr;
        VlWide<8>/*255:0*/ tb_gpu_top__DOT__dut__DOT__dmem_rdata;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT____Vcellout__regfiles__BRA__0__KET____DOT__u_regfile__rs2_data;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT____Vcellout__regfiles__BRA__0__KET____DOT__u_regfile__rs1_data;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT____Vcellout__lanes__BRA__0__KET____DOT__u_lane__branch_target;
        QData/*63:0*/ tb_gpu_top__DOT__dut__DOT__u_scheduler__DOT__warp_pc;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__u_scheduler__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__u_scheduler__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__u_scheduler__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__u_scheduler__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__u_decode__DOT__imm_i;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__u_decode__DOT__imm;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__regfiles__BRA__0__KET____DOT__u_regfile__DOT____Vlvbound_hec9a31ed__0;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__regfiles__BRA__1__KET____DOT__u_regfile__DOT____Vlvbound_hec9a31ed__0;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__regfiles__BRA__2__KET____DOT__u_regfile__DOT____Vlvbound_hec9a31ed__0;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__regfiles__BRA__3__KET____DOT__u_regfile__DOT____Vlvbound_hec9a31ed__0;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__regfiles__BRA__4__KET____DOT__u_regfile__DOT____Vlvbound_hec9a31ed__0;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__regfiles__BRA__5__KET____DOT__u_regfile__DOT____Vlvbound_hec9a31ed__0;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__regfiles__BRA__6__KET____DOT__u_regfile__DOT____Vlvbound_hec9a31ed__0;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__regfiles__BRA__7__KET____DOT__u_regfile__DOT____Vlvbound_hec9a31ed__0;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__lanes__BRA__0__KET____DOT__u_lane__DOT__alu_b;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__lanes__BRA__0__KET____DOT__u_lane__DOT__alu_in_a;
        IData/*31:0*/ tb_gpu_top__DOT__dut__DOT__lanes__BRA__0__KET____DOT__u_lane__DOT__alu_result;
        IData/*31:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v6;
        IData/*31:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v13;
        IData/*31:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v20;
        IData/*31:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v27;
        IData/*31:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v34;
        IData/*31:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v41;
        IData/*31:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v48;
        IData/*31:0*/ __Vdlyvval__tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem__v55;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<IData/*31:0*/, 8> tb_gpu_top__DOT__dut__DOT__id_rs1_data;
        VlUnpacked<IData/*31:0*/, 8> tb_gpu_top__DOT__dut__DOT__id_rs2_data;
        VlUnpacked<CData/*0:0*/, 8> tb_gpu_top__DOT__dut__DOT__wb_wen;
        VlUnpacked<CData/*4:0*/, 8> tb_gpu_top__DOT__dut__DOT__wb_rd_addr;
        VlUnpacked<IData/*31:0*/, 8> tb_gpu_top__DOT__dut__DOT__wb_data;
        VlUnpacked<CData/*0:0*/, 8> tb_gpu_top__DOT__dut__DOT__wb_warp_id;
        VlUnpacked<IData/*31:0*/, 8> tb_gpu_top__DOT__dut__DOT__rf_rs1;
        VlUnpacked<IData/*31:0*/, 8> tb_gpu_top__DOT__dut__DOT__rf_rs2;
        VlUnpacked<CData/*0:0*/, 2> tb_gpu_top__DOT__dut__DOT__u_scheduler__DOT__warp_state;
        VlUnpacked<IData/*31:0*/, 1024> tb_gpu_top__DOT__dut__DOT__u_fetch__DOT__imem;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 256>, 8> tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__mem;
        VlUnpacked<CData/*7:0*/, 8> tb_gpu_top__DOT__dut__DOT__u_scratchpad__DOT__word_addr;
        VlUnpacked<VlUnpacked<VlUnpacked<IData/*31:0*/, 31>, 8>, 2> tb_gpu_top__DOT__dut__DOT__regfiles__BRA__0__KET____DOT__u_regfile__DOT__regs;
        VlUnpacked<VlUnpacked<VlUnpacked<IData/*31:0*/, 31>, 8>, 2> tb_gpu_top__DOT__dut__DOT__regfiles__BRA__1__KET____DOT__u_regfile__DOT__regs;
        VlUnpacked<VlUnpacked<VlUnpacked<IData/*31:0*/, 31>, 8>, 2> tb_gpu_top__DOT__dut__DOT__regfiles__BRA__2__KET____DOT__u_regfile__DOT__regs;
        VlUnpacked<VlUnpacked<VlUnpacked<IData/*31:0*/, 31>, 8>, 2> tb_gpu_top__DOT__dut__DOT__regfiles__BRA__3__KET____DOT__u_regfile__DOT__regs;
        VlUnpacked<VlUnpacked<VlUnpacked<IData/*31:0*/, 31>, 8>, 2> tb_gpu_top__DOT__dut__DOT__regfiles__BRA__4__KET____DOT__u_regfile__DOT__regs;
        VlUnpacked<VlUnpacked<VlUnpacked<IData/*31:0*/, 31>, 8>, 2> tb_gpu_top__DOT__dut__DOT__regfiles__BRA__5__KET____DOT__u_regfile__DOT__regs;
        VlUnpacked<VlUnpacked<VlUnpacked<IData/*31:0*/, 31>, 8>, 2> tb_gpu_top__DOT__dut__DOT__regfiles__BRA__6__KET____DOT__u_regfile__DOT__regs;
        VlUnpacked<VlUnpacked<VlUnpacked<IData/*31:0*/, 31>, 8>, 2> tb_gpu_top__DOT__dut__DOT__regfiles__BRA__7__KET____DOT__u_regfile__DOT__regs;
        VlUnpacked<CData/*0:0*/, 5> __Vm_traceActivity;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_h4954a85e__0;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<3> __VactTriggered;
    VlTriggerVec<3> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtb_gpu_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb_gpu_top___024root(Vtb_gpu_top__Syms* symsp, const char* v__name);
    ~Vtb_gpu_top___024root();
    VL_UNCOPYABLE(Vtb_gpu_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
